module.exports = {
  prons: [
    {"word":"and","pron":"AH0 N D .","syllables":[0]},
    {"word":"of","pron":"AH1 V .","syllables":[1]},
    {"word":"to","pron":"T UW1 .","syllables":[1]},
    {"word":"in","pron":"IH0 N .","syllables":[0]},
    {"word":"it","pron":"IH1 T .","syllables":[1]},
    {"word":"a","pron":"AH0 .","syllables":[0]},
    {"word":"the","pron":"DH AH0 .","syllables":[0]},
    {"word":"is","pron":"IH1 Z .","syllables":[1]},
    {"word":"for","pron":"F AO1 R .","syllables":[1]},
    {"word":"they","pron":"DH EY1 .","syllables":[1]},
    {"word":"two","pron":"T UW1 .","syllables":[1]},
    {"word":"be","pron":"B IY1 .","syllables":[1]},
    {"word":"will","pron":"W IH1 L .","syllables":[1]},
    {"word":"on","pron":"AA1 N .","syllables":[1]},
    {"word":"you","pron":"Y UW1 .","syllables":[1]},
    {"word":"when","pron":"W EH1 N .","syllables":[1]},
    {"word":"that","pron":"DH AE1 T .","syllables":[1]},
    {"word":"like","pron":"L AY1 K .","syllables":[1]},
    {"word":"up","pron":"AH1 P .","syllables":[1]},
    {"word":"about","pron":"AH0 B AW1 T .","syllables":[0,1]},
    {"word":"are","pron":"AA1 R .","syllables":[1]},
    {"word":"this","pron":"DH IH1 S .","syllables":[1]},
    {"word":"all","pron":"AO1 L .","syllables":[1]},
    {"word":"can","pron":"K AE1 N .","syllables":[1]},
    {"word":"not","pron":"N AA1 T .","syllables":[1]},
    {"word":"write","pron":"R AY1 T .","syllables":[1]},
    {"word":"her","pron":"HH ER1 .","syllables":[1]},
    {"word":"but","pron":"B AH1 T .","syllables":[1]},
    {"word":"by","pron":"B AY1 .","syllables":[1]},
    {"word":"then","pron":"DH EH1 N .","syllables":[1]},
    {"word":"what","pron":"W AH1 T .","syllables":[1]},
    {"word":"some","pron":"S AH1 M .","syllables":[1]},
    {"word":"your","pron":"Y AO1 R .","syllables":[1]},
    {"word":"said","pron":"S EH1 D .","syllables":[1]},
    {"word":"how","pron":"HH AW1 .","syllables":[1]},
    {"word":"had","pron":"HH AE1 D .","syllables":[1]},
    {"word":"each","pron":"IY1 CH .","syllables":[1]},
    {"word":"would","pron":"W UH1 D .","syllables":[1]},
    {"word":"word","pron":"W ER1 D .","syllables":[1]},
    {"word":"could","pron":"K UH1 D .","syllables":[1]},
    {"word":"as","pron":"AE1 Z .","syllables":[1]},
    {"word":"did","pron":"D IH1 D .","syllables":[1]},
    {"word":"people","pron":"P IY1 P AH0 L .","syllables":[1,0]},
    {"word":"see","pron":"S IY1 .","syllables":[1]},
    {"word":"go","pron":"G OW1 .","syllables":[1]},
    {"word":"day","pron":"D EY1 .","syllables":[1]},
    {"word":"more","pron":"M AO1 R .","syllables":[1]},
    {"word":"which","pron":"W IH1 CH .","syllables":[1]},
    {"word":"know","pron":"N OW1 .","syllables":[1]},
    {"word":"sound","pron":"S AW1 N D .","syllables":[1]},
    {"word":"most","pron":"M OW1 S T .","syllables":[1]},
    {"word":"no","pron":"N OW1 .","syllables":[1]},
    {"word":"down","pron":"D AW1 N .","syllables":[1]},
    {"word":"than","pron":"DH AE1 N .","syllables":[1]},
    {"word":"first","pron":"F ER1 S T .","syllables":[1]},
    {"word":"come","pron":"K AH1 M .","syllables":[1]},
    {"word":"my","pron":"M AY1 .","syllables":[1]},
    {"word":"over","pron":"OW1 V ER0 .","syllables":[1,0]},
    {"word":"number","pron":"N AH1 M B ER0 .","syllables":[1,0]},
    {"word":"call","pron":"K AO1 L .","syllables":[1]},
    {"word":"water","pron":"W AO1 T ER0 .","syllables":[1,0]},
    {"word":"side","pron":"S AY1 D .","syllables":[1]},
    {"word":"may","pron":"M EY1 .","syllables":[1]},
    {"word":"been","pron":"B IH1 N .","syllables":[1]},
    {"word":"who","pron":"HH UW1 .","syllables":[1]},
    {"word":"now","pron":"N AW1 .","syllables":[1]},
    {"word":"his","pron":"HH IH1 Z .","syllables":[1]},
    {"word":"look","pron":"L UH1 K .","syllables":[1]},
    {"word":"find","pron":"F AY1 N D .","syllables":[1]},
    {"word":"them","pron":"DH EH1 M .","syllables":[1]},
    {"word":"him","pron":"HH IH1 M .","syllables":[1]},
    {"word":"he","pron":"HH IY1 .","syllables":[1]},
    {"word":"an","pron":"AE1 N .","syllables":[1]},
    {"word":"with","pron":"W IH1 DH .","syllables":[1]},
    {"word":"make","pron":"M EY1 K .","syllables":[1]},
    {"word":"if","pron":"IH1 F .","syllables":[1]},
    {"word":"these","pron":"DH IY1 Z .","syllables":[1]},
    {"word":"we","pron":"W IY1 .","syllables":[1]},
    {"word":"from","pron":"F R AH1 M .","syllables":[1]},
    {"word":"was","pron":"W AA1 Z .","syllables":[1]},
    {"word":"has","pron":"HH AE1 Z .","syllables":[1]},
    {"word":"so","pron":"S OW1 .","syllables":[1]},
    {"word":"out","pron":"AW1 T .","syllables":[1]},
    {"word":"thing","pron":"TH IH1 NG .","syllables":[1]},
    {"word":"many","pron":"M EH1 N IY0 .","syllables":[1,0]},
    {"word":"other","pron":"AH1 DH ER0 .","syllables":[1,0]},
    {"word":"way","pron":"W EY1 .","syllables":[1]},
    {"word":"their","pron":"DH EH1 R .","syllables":[1]},
    {"word":"time","pron":"T AY1 M .","syllables":[1]},
    {"word":"there","pron":"DH EH1 R .","syllables":[1]},
    {"word":"use","pron":"Y UW1 S .","syllables":[1]},
    {"word":"she","pron":"SH IY1 .","syllables":[1]},
    {"word":"were","pron":"W ER1 .","syllables":[1]},
    {"word":"one","pron":"W AH1 N .","syllables":[1]},
    {"word":"long","pron":"L AO1 NG .","syllables":[1]},
    {"word":"or","pron":"AO1 R .","syllables":[1]},
    {"word":"at","pron":"AE1 T .","syllables":[1]},
    {"word":"I","pron":"AY1 .","syllables":[1]},
    {"word":"have","pron":"HH AE1 V .","syllables":[1]},
    {"word":"do","pron":"D UW1 .","syllables":[1]},
    {"word":"take","pron":"T EY1 K .","syllables":[1]},
    {"word":"any","pron":"EH1 N IY0 .","syllables":[1,0]},
    {"word":"work","pron":"W ER1 K .","syllables":[1]},
    {"word":"place","pron":"P L EY1 S .","syllables":[1]},
    {"word":"sentence","pron":"S EH1 N T AH0 N S .","syllables":[1,0]},
    {"word":"three","pron":"TH R IY1 .","syllables":[1]},
    {"word":"new","pron":"N UW1 .","syllables":[1]},
    {"word":"where","pron":"W EH1 R .","syllables":[1]},
    {"word":"help","pron":"HH EH1 L P .","syllables":[1]},
    {"word":"part","pron":"P AA1 R T .","syllables":[1]},
    {"word":"made","pron":"M EY1 D .","syllables":[1]},
    {"word":"show","pron":"SH OW1 .","syllables":[1]},
    {"word":"much","pron":"M AH1 CH .","syllables":[1]},
    {"word":"live","pron":"L AY1 V .","syllables":[1]},
    {"word":"form","pron":"F AO1 R M .","syllables":[1]},
    {"word":"man","pron":"M AE1 N .","syllables":[1]},
    {"word":"line","pron":"L AY1 N .","syllables":[1]},
    {"word":"every","pron":"EH1 V ER0 IY0 .","syllables":[1,0,0]},
    {"word":"came","pron":"K EY1 M .","syllables":[1]},
    {"word":"cause","pron":"K AA1 Z .","syllables":[1]},
    {"word":"low","pron":"L OW1 .","syllables":[1]},
    {"word":"very","pron":"V EH1 R IY0 .","syllables":[1,0]},
    {"word":"right","pron":"R AY1 T .","syllables":[1]},
    {"word":"get","pron":"G EH1 T .","syllables":[1]},
    {"word":"put","pron":"P UH1 T .","syllables":[1]},
    {"word":"also","pron":"AO1 L S OW0 .","syllables":[1,0]},
    {"word":"set","pron":"S EH1 T .","syllables":[1]},
    {"word":"spell","pron":"S P EH1 L .","syllables":[1]},
    {"word":"read","pron":"R EH1 D .","syllables":[1]},
    {"word":"give","pron":"G IH1 V .","syllables":[1]},
    {"word":"move","pron":"M UW1 V .","syllables":[1]},
    {"word":"too","pron":"T UW1 .","syllables":[1]},
    {"word":"good","pron":"G UH1 D .","syllables":[1]},
    {"word":"me","pron":"M IY1 .","syllables":[1]},
    {"word":"before","pron":"B IH0 F AO1 R .","syllables":[0,1]},
    {"word":"same","pron":"S EY1 M .","syllables":[1]},
    {"word":"tell","pron":"T EH1 L .","syllables":[1]},
    {"word":"men","pron":"M EH1 N .","syllables":[1]},
    {"word":"change","pron":"CH EY1 N JH .","syllables":[1]},
    {"word":"port","pron":"P AO1 R T .","syllables":[1]},
    {"word":"follow","pron":"F AA1 L OW0 .","syllables":[1,0]},
    {"word":"large","pron":"L AA1 R JH .","syllables":[1]},
    {"word":"add","pron":"AE1 D .","syllables":[1]},
    {"word":"why","pron":"W AY1 .","syllables":[1]},
    {"word":"picture","pron":"P IH1 K CH ER0 .","syllables":[1,0]},
    {"word":"act","pron":"AE1 K T .","syllables":[1]},
    {"word":"house","pron":"HH AW1 S .","syllables":[1]},
    {"word":"such","pron":"S AH1 CH .","syllables":[1]},
    {"word":"light","pron":"L AY1 T .","syllables":[1]},
    {"word":"went","pron":"W EH1 N T .","syllables":[1]},
    {"word":"ask","pron":"AE1 S K .","syllables":[1]},
    {"word":"off","pron":"AO1 F .","syllables":[1]},
    {"word":"kind","pron":"K AY1 N D .","syllables":[1]},
    {"word":"even","pron":"IY1 V IH0 N .","syllables":[1,0]},
    {"word":"build","pron":"B IH1 L D .","syllables":[1]},
    {"word":"near","pron":"N IH1 R .","syllables":[1]},
    {"word":"animal","pron":"AE1 N AH0 M AH0 L .","syllables":[1,0,0]},
    {"word":"again","pron":"AH0 G EH1 N .","syllables":[0,1]},
    {"word":"try","pron":"T R AY1 .","syllables":[1]},
    {"word":"us","pron":"AH1 S .","syllables":[1]},
    {"word":"mother","pron":"M AH1 DH ER0 .","syllables":[1,0]},
    {"word":"earth","pron":"ER1 TH .","syllables":[1]},
    {"word":"father","pron":"F AA1 DH ER0 .","syllables":[1,0]},
    {"word":"hand","pron":"HH AE1 N D .","syllables":[1]},
    {"word":"need","pron":"N IY1 D .","syllables":[1]},
    {"word":"world","pron":"W ER1 L D .","syllables":[1]},
    {"word":"point","pron":"P OY1 N T .","syllables":[1]},
    {"word":"self","pron":"S EH1 L F .","syllables":[1]},
    {"word":"year","pron":"Y IH1 R .","syllables":[1]},
    {"word":"round","pron":"R AW1 N D .","syllables":[1]},
    {"word":"say","pron":"S EY1 .","syllables":[1]},
    {"word":"little","pron":"L IH1 T AH0 L .","syllables":[1,0]},
    {"word":"air","pron":"EH1 R .","syllables":[1]},
    {"word":"turn","pron":"T ER1 N .","syllables":[1]},
    {"word":"well","pron":"W EH1 L .","syllables":[1]},
    {"word":"only","pron":"OW1 N L IY0 .","syllables":[1,0]},
    {"word":"after","pron":"AE1 F T ER0 .","syllables":[1,0]},
    {"word":"our","pron":"AW1 ER0 .","syllables":[1,0]},
    {"word":"mean","pron":"M IY1 N .","syllables":[1]},
    {"word":"land","pron":"L AE1 N D .","syllables":[1]},
    {"word":"name","pron":"N EY1 M .","syllables":[1]},
    {"word":"back","pron":"B AE1 K .","syllables":[1]},
    {"word":"here","pron":"HH IY1 R .","syllables":[1]},
    {"word":"think","pron":"TH IH1 NG K .","syllables":[1]},
    {"word":"boy","pron":"B OY1 .","syllables":[1]},
    {"word":"through","pron":"TH R UW1 .","syllables":[1]},
    {"word":"differ","pron":"D IH1 F ER0 .","syllables":[1,0]},
    {"word":"great","pron":"G R EY1 T .","syllables":[1]},
    {"word":"must","pron":"M AH1 S T .","syllables":[1]},
    {"word":"high","pron":"HH AY1 .","syllables":[1]},
    {"word":"does","pron":"D AH1 Z .","syllables":[1]},
    {"word":"want","pron":"W AA1 N T .","syllables":[1]},
    {"word":"under","pron":"AH1 N D ER0 .","syllables":[1,0]},
    {"word":"just","pron":"JH AH1 S T .","syllables":[1]},
    {"word":"home","pron":"HH OW1 M .","syllables":[1]},
    {"word":"play","pron":"P L EY1 .","syllables":[1]},
    {"word":"big","pron":"B IH1 G .","syllables":[1]},
    {"word":"old","pron":"OW1 L D .","syllables":[1]},
    {"word":"end","pron":"EH1 N D .","syllables":[1]},
    {"word":"small","pron":"S M AO1 L .","syllables":[1]},
    {"word":"page","pron":"P EY1 JH .","syllables":[1]},
    {"word":"study","pron":"S T AH1 D IY0 .","syllables":[1,0]},
    {"word":"still","pron":"S T IH1 L .","syllables":[1]},
    {"word":"together","pron":"T AH0 G EH1 DH ER0 .","syllables":[0,1,0]},
    {"word":"stand","pron":"S T AE1 N D .","syllables":[1]},
    {"word":"got","pron":"G AA1 T .","syllables":[1]},
    {"word":"state","pron":"S T EY1 T .","syllables":[1]},
    {"word":"between","pron":"B IH0 T W IY1 N .","syllables":[0,1]},
    {"word":"head","pron":"HH EH1 D .","syllables":[1]},
    {"word":"cross","pron":"K R AO1 S .","syllables":[1]},
    {"word":"country","pron":"K AH1 N T R IY0 .","syllables":[1,0]},
    {"word":"left","pron":"L EH1 F T .","syllables":[1]},
    {"word":"eye","pron":"AY1 .","syllables":[1]},
    {"word":"those","pron":"DH OW1 Z .","syllables":[1]},
    {"word":"found","pron":"F AW1 N D .","syllables":[1]},
    {"word":"should","pron":"SH UH1 D .","syllables":[1]},
    {"word":"let","pron":"L EH1 T .","syllables":[1]},
    {"word":"late","pron":"L EY1 T .","syllables":[1]},
    {"word":"last","pron":"L AE1 S T .","syllables":[1]},
    {"word":"answer","pron":"AE1 N S ER0 .","syllables":[1,0]},
    {"word":"own","pron":"OW1 N .","syllables":[1]},
    {"word":"never","pron":"N EH1 V ER0 .","syllables":[1,0]},
    {"word":"press","pron":"P R EH1 S .","syllables":[1]},
    {"word":"white","pron":"W AY1 T .","syllables":[1]},
    {"word":"example","pron":"IH0 G Z AE1 M P AH0 L .","syllables":[0,1,0]},
    {"word":"draw","pron":"D R AO1 .","syllables":[1]},
    {"word":"keep","pron":"K IY1 P .","syllables":[1]},
    {"word":"sure","pron":"SH UH1 R .","syllables":[1]},
    {"word":"run","pron":"R AH1 N .","syllables":[1]},
    {"word":"while","pron":"W AY1 L .","syllables":[1]},
    {"word":"friend","pron":"F R EH1 N D .","syllables":[1]},
    {"word":"paper","pron":"P EY1 P ER0 .","syllables":[1,0]},
    {"word":"horse","pron":"HH AO1 R S .","syllables":[1]},
    {"word":"science","pron":"S AY1 AH0 N S .","syllables":[1,0]},
    {"word":"feet","pron":"F IY1 T .","syllables":[1]},
    {"word":"began","pron":"B IH0 G AE1 N .","syllables":[0,1]},
    {"word":"second","pron":"S EH1 K AH0 N D .","syllables":[1,0]},
    {"word":"always","pron":"AO1 L W EY2 Z .","syllables":[1,2]},
    {"word":"sea","pron":"S IY1 .","syllables":[1]},
    {"word":"idea","pron":"AY0 D IY1 AH0 .","syllables":[0,1,0]},
    {"word":"fish","pron":"F IH1 SH .","syllables":[1]},
    {"word":"far","pron":"F AA1 R .","syllables":[1]},
    {"word":"room","pron":"R UW1 M .","syllables":[1]},
    {"word":"main","pron":"M EY1 N .","syllables":[1]},
    {"word":"eat","pron":"IY1 T .","syllables":[1]},
    {"word":"watch","pron":"W AA1 CH .","syllables":[1]},
    {"word":"seem","pron":"S IY1 M .","syllables":[1]},
    {"word":"hear","pron":"HH IY1 R .","syllables":[1]},
    {"word":"cut","pron":"K AH1 T .","syllables":[1]},
    {"word":"wood","pron":"W UH1 D .","syllables":[1]},
    {"word":"stop","pron":"S T AA1 P .","syllables":[1]},
    {"word":"took","pron":"T UH1 K .","syllables":[1]},
    {"word":"color","pron":"K AH1 L ER0 .","syllables":[1,0]},
    {"word":"children","pron":"CH IH1 L D R AH0 N .","syllables":[1,0]},
    {"word":"don't","pron":"D OW1 N T .","syllables":[1]},
    {"word":"close","pron":"K L OW1 S .","syllables":[1]},
    {"word":"story","pron":"S T AO1 R IY0 .","syllables":[1,0]},
    {"word":"carry","pron":"K AE1 R IY0 .","syllables":[1,0]},
    {"word":"saw","pron":"S AO1 .","syllables":[1]},
    {"word":"face","pron":"F EY1 S .","syllables":[1]},
    {"word":"four","pron":"F AO1 R .","syllables":[1]},
    {"word":"food","pron":"F UW1 D .","syllables":[1]},
    {"word":"grow","pron":"G R OW1 .","syllables":[1]},
    {"word":"cover","pron":"K AH1 V ER0 .","syllables":[1,0]},
    {"word":"walk","pron":"W AO1 K .","syllables":[1]},
    {"word":"real","pron":"R IY1 L .","syllables":[1]},
    {"word":"book","pron":"B UH1 K .","syllables":[1]},
    {"word":"life","pron":"L AY1 F .","syllables":[1]},
    {"word":"plant","pron":"P L AE1 N T .","syllables":[1]},
    {"word":"open","pron":"OW1 P AH0 N .","syllables":[1,0]},
    {"word":"learn","pron":"L ER1 N .","syllables":[1]},
    {"word":"thought","pron":"TH AO1 T .","syllables":[1]},
    {"word":"next","pron":"N EH1 K S T .","syllables":[1]},
    {"word":"night","pron":"N AY1 T .","syllables":[1]},
    {"word":"farm","pron":"F AA1 R M .","syllables":[1]},
    {"word":"sun","pron":"S AH1 N .","syllables":[1]},
    {"word":"mile","pron":"M AY1 L .","syllables":[1]},
    {"word":"might","pron":"M AY1 T .","syllables":[1]},
    {"word":"music","pron":"M Y UW1 Z IH0 K .","syllables":[1,0]},
    {"word":"few","pron":"F Y UW1 .","syllables":[1]},
    {"word":"start","pron":"S T AA1 R T .","syllables":[1]},
    {"word":"both","pron":"B OW1 TH .","syllables":[1]},
    {"word":"tree","pron":"T R IY1 .","syllables":[1]},
    {"word":"until","pron":"AH0 N T IH1 L .","syllables":[0,1]},
    {"word":"hard","pron":"HH AA1 R D .","syllables":[1]},
    {"word":"ease","pron":"IY1 Z .","syllables":[1]},
    {"word":"mark","pron":"M AA1 R K .","syllables":[1]},
    {"word":"often","pron":"AO1 F T AH0 N .","syllables":[1,0]},
    {"word":"car","pron":"K AA1 R .","syllables":[1]},
    {"word":"mountain","pron":"M AW1 N T AH0 N .","syllables":[1,0]},
    {"word":"once","pron":"W AH1 N S .","syllables":[1]},
    {"word":"north","pron":"N AO1 R TH .","syllables":[1]},
    {"word":"base","pron":"B EY1 S .","syllables":[1]},
    {"word":"school","pron":"S K UW1 L .","syllables":[1]},
    {"word":"group","pron":"G R UW1 P .","syllables":[1]},
    {"word":"begin","pron":"B IH0 G IH1 N .","syllables":[0,1]},
    {"word":"letter","pron":"L EH1 T ER0 .","syllables":[1,0]},
    {"word":"city","pron":"S IH1 T IY0 .","syllables":[1,0]},
    {"word":"care","pron":"K EH1 R .","syllables":[1]},
    {"word":"river","pron":"R IH1 V ER0 .","syllables":[1,0]},
    {"word":"enough","pron":"IH0 N AH1 F .","syllables":[0,1]},
    {"word":"leave","pron":"L IY1 V .","syllables":[1]},
    {"word":"young","pron":"Y AH1 NG .","syllables":[1]},
    {"word":"girl","pron":"G ER1 L .","syllables":[1]},
    {"word":"list","pron":"L IH1 S T .","syllables":[1]},
    {"word":"short","pron":"SH AO1 R T .","syllables":[1]},
    {"word":"ready","pron":"R EH1 D IY0 .","syllables":[1,0]},
    {"word":"usual","pron":"Y UW1 ZH AH0 W AH0 L .","syllables":[1,0,0]},
    {"word":"measure","pron":"M EH1 ZH ER0 .","syllables":[1,0]},
    {"word":"product","pron":"P R AA1 D AH0 K T .","syllables":[1,0]},
    {"word":"ever","pron":"EH1 V ER0 .","syllables":[1,0]},
    {"word":"order","pron":"AO1 R D ER0 .","syllables":[1,0]},
    {"word":"black","pron":"B L AE1 K .","syllables":[1]},
    {"word":"pose","pron":"P OW1 Z .","syllables":[1]},
    {"word":"half","pron":"HH AE1 F .","syllables":[1]},
    {"word":"plain","pron":"P L EY1 N .","syllables":[1]},
    {"word":"above","pron":"AH0 B AH1 V .","syllables":[0,1]},
    {"word":"rock","pron":"R AA1 K .","syllables":[1]},
    {"word":"space","pron":"S P EY1 S .","syllables":[1]},
    {"word":"though","pron":"DH OW1 .","syllables":[1]},
    {"word":"better","pron":"B EH1 T ER0 .","syllables":[1,0]},
    {"word":"best","pron":"B EH1 S T .","syllables":[1]},
    {"word":"told","pron":"T OW1 L D .","syllables":[1]},
    {"word":"soon","pron":"S UW1 N .","syllables":[1]},
    {"word":"true","pron":"T R UW1 .","syllables":[1]},
    {"word":"door","pron":"D AO1 R .","syllables":[1]},
    {"word":"red","pron":"R EH1 D .","syllables":[1]},
    {"word":"vowel","pron":"V AW1 AH0 L .","syllables":[1,0]},
    {"word":"listen","pron":"L IH1 S AH0 N .","syllables":[1,0]},
    {"word":"fire","pron":"F AY1 ER0 .","syllables":[1,0]},
    {"word":"complete","pron":"K AH0 M P L IY1 T .","syllables":[0,1]},
    {"word":"fast","pron":"F AE1 S T .","syllables":[1]},
    {"word":"hour","pron":"AW1 ER0 .","syllables":[1,0]},
    {"word":"interest","pron":"IH1 N T AH0 R EH2 S T .","syllables":[1,0,2]},
    {"word":"pattern","pron":"P AE1 T ER0 N .","syllables":[1,0]},
    {"word":"five","pron":"F AY1 V .","syllables":[1]},
    {"word":"gave","pron":"G EY1 V .","syllables":[1]},
    {"word":"quick","pron":"K W IH1 K .","syllables":[1]},
    {"word":"early","pron":"ER1 L IY0 .","syllables":[1,0]},
    {"word":"slow","pron":"S L OW1 .","syllables":[1]},
    {"word":"war","pron":"W AO1 R .","syllables":[1]},
    {"word":"lay","pron":"L EY1 .","syllables":[1]},
    {"word":"certain","pron":"S ER1 T AH0 N .","syllables":[1,0]},
    {"word":"free","pron":"F R IY1 .","syllables":[1]},
    {"word":"reach","pron":"R IY1 CH .","syllables":[1]},
    {"word":"center","pron":"S EH1 N T ER0 .","syllables":[1,0]},
    {"word":"ground","pron":"G R AW1 N D .","syllables":[1]},
    {"word":"govern","pron":"G AH1 V ER0 N .","syllables":[1,0]},
    {"word":"love","pron":"L AH1 V .","syllables":[1]},
    {"word":"mind","pron":"M AY1 N D .","syllables":[1]},
    {"word":"clear","pron":"K L IH1 R .","syllables":[1]},
    {"word":"minute","pron":"M IH1 N AH0 T .","syllables":[1,0]},
    {"word":"travel","pron":"T R AE1 V AH0 L .","syllables":[1,0]},
    {"word":"money","pron":"M AH1 N IY0 .","syllables":[1,0]},
    {"word":"correct","pron":"K ER0 EH1 K T .","syllables":[0,1]},
    {"word":"fine","pron":"F AY1 N .","syllables":[1]},
    {"word":"power","pron":"P AW1 ER0 .","syllables":[1,0]},
    {"word":"star","pron":"S T AA1 R .","syllables":[1]},
    {"word":"sing","pron":"S IH1 NG .","syllables":[1]},
    {"word":"wheel","pron":"W IY1 L .","syllables":[1]},
    {"word":"wait","pron":"W EY1 T .","syllables":[1]},
    {"word":"drive","pron":"D R AY1 V .","syllables":[1]},
    {"word":"field","pron":"F IY1 L D .","syllables":[1]},
    {"word":"figure","pron":"F IH1 G Y ER0 .","syllables":[1,0]},
    {"word":"noun","pron":"N AW1 N .","syllables":[1]},
    {"word":"special","pron":"S P EH1 SH AH0 L .","syllables":[1,0]},
    {"word":"notice","pron":"N OW1 T AH0 S .","syllables":[1,0]},
    {"word":"box","pron":"B AA1 K S .","syllables":[1]},
    {"word":"unit","pron":"Y UW1 N AH0 T .","syllables":[1,0]},
    {"word":"island","pron":"AY1 L AH0 N D .","syllables":[1,0]},
    {"word":"moon","pron":"M UW1 N .","syllables":[1]},
    {"word":"test","pron":"T EH1 S T .","syllables":[1]},
    {"word":"nothing","pron":"N AH1 TH IH0 NG .","syllables":[1,0]},
    {"word":"surface","pron":"S ER1 F AH0 S .","syllables":[1,0]},
    {"word":"produce","pron":"P R AH0 D UW1 S .","syllables":[0,1]},
    {"word":"fact","pron":"F AE1 K T .","syllables":[1]},
    {"word":"street","pron":"S T R IY1 T .","syllables":[1]},
    {"word":"foot","pron":"F UH1 T .","syllables":[1]},
    {"word":"inch","pron":"IH1 N CH .","syllables":[1]},
    {"word":"object","pron":"AA1 B JH EH0 K T .","syllables":[1,0]},
    {"word":"decide","pron":"D IH2 S AY1 D .","syllables":[2,1]},
    {"word":"dry","pron":"D R AY1 .","syllables":[1]},
    {"word":"common","pron":"K AA1 M AH0 N .","syllables":[1,0]},
    {"word":"plane","pron":"P L EY1 N .","syllables":[1]},
    {"word":"thousand","pron":"TH AW1 Z AH0 N D .","syllables":[1,0]},
    {"word":"record","pron":"R AH0 K AO1 R D .","syllables":[0,1]},
    {"word":"miss","pron":"M IH1 S .","syllables":[1]},
    {"word":"ran","pron":"R AE1 N .","syllables":[1]},
    {"word":"wonder","pron":"W AH1 N D ER0 .","syllables":[1,0]},
    {"word":"possible","pron":"P AA1 S AH0 B AH0 L .","syllables":[1,0,0]},
    {"word":"boat","pron":"B OW1 T .","syllables":[1]},
    {"word":"fill","pron":"F IH1 L .","syllables":[1]},
    {"word":"distant","pron":"D IH1 S T AH0 N T .","syllables":[1,0]},
    {"word":"check","pron":"CH EH1 K .","syllables":[1]},
    {"word":"shape","pron":"SH EY1 P .","syllables":[1]},
    {"word":"among","pron":"AH0 M AH1 NG .","syllables":[0,1]},
    {"word":"stead","pron":"S T EH1 D .","syllables":[1]},
    {"word":"tire","pron":"T AY1 ER0 .","syllables":[1,0]},
    {"word":"hot","pron":"HH AA1 T .","syllables":[1]},
    {"word":"snow","pron":"S N OW1 .","syllables":[1]},
    {"word":"east","pron":"IY1 S T .","syllables":[1]},
    {"word":"heat","pron":"HH IY1 T .","syllables":[1]},
    {"word":"yes","pron":"Y EH1 S .","syllables":[1]},
    {"word":"paint","pron":"P EY1 N T .","syllables":[1]},
    {"word":"bring","pron":"B R IH1 NG .","syllables":[1]},
    {"word":"brought","pron":"B R AO1 T .","syllables":[1]},
    {"word":"ship","pron":"SH IH1 P .","syllables":[1]},
    {"word":"south","pron":"S AW1 TH .","syllables":[1]},
    {"word":"strong","pron":"S T R AO1 NG .","syllables":[1]},
    {"word":"heard","pron":"HH ER1 D .","syllables":[1]},
    {"word":"song","pron":"S AO1 NG .","syllables":[1]},
    {"word":"equate","pron":"IH0 K W EY1 T .","syllables":[0,1]},
    {"word":"during","pron":"D UH1 R IH0 NG .","syllables":[1,0]},
    {"word":"deep","pron":"D IY1 P .","syllables":[1]},
    {"word":"ago","pron":"AH0 G OW1 .","syllables":[0,1]},
    {"word":"game","pron":"G EY1 M .","syllables":[1]},
    {"word":"language","pron":"L AE1 NG G W AH0 JH .","syllables":[1,0]},
    {"word":"appear","pron":"AH0 P IH1 R .","syllables":[0,1]},
    {"word":"pull","pron":"P UH1 L .","syllables":[1]},
    {"word":"system","pron":"S IH1 S T AH0 M .","syllables":[1,0]},
    {"word":"busy","pron":"B IH1 Z IY0 .","syllables":[1,0]},
    {"word":"force","pron":"F AO1 R S .","syllables":[1]},
    {"word":"laugh","pron":"L AE1 F .","syllables":[1]},
    {"word":"gold","pron":"G OW1 L D .","syllables":[1]},
    {"word":"blue","pron":"B L UW1 .","syllables":[1]},
    {"word":"multiply","pron":"M AH1 L T AH0 P L AY2 .","syllables":[1,0,2]},
    {"word":"stay","pron":"S T EY1 .","syllables":[1]},
    {"word":"course","pron":"K AO1 R S .","syllables":[1]},
    {"word":"body","pron":"B AA1 D IY0 .","syllables":[1,0]},
    {"word":"piece","pron":"P IY1 S .","syllables":[1]},
    {"word":"dog","pron":"D AO1 G .","syllables":[1]},
    {"word":"feel","pron":"F IY1 L .","syllables":[1]},
    {"word":"knew","pron":"N UW1 .","syllables":[1]},
    {"word":"question","pron":"K W EH1 S CH AH0 N .","syllables":[1,0]},
    {"word":"direct","pron":"D ER0 EH1 K T .","syllables":[0,1]},
    {"word":"king","pron":"K IH1 NG .","syllables":[1]},
    {"word":"pass","pron":"P AE1 S .","syllables":[1]},
    {"word":"ten","pron":"T EH1 N .","syllables":[1]},
    {"word":"talk","pron":"T AO1 K .","syllables":[1]},
    {"word":"voice","pron":"V OY1 S .","syllables":[1]},
    {"word":"whole","pron":"HH OW1 L .","syllables":[1]},
    {"word":"since","pron":"S IH1 N S .","syllables":[1]},
    {"word":"top","pron":"T AA1 P .","syllables":[1]},
    {"word":"family","pron":"F AE1 M AH0 L IY0 .","syllables":[1,0,0]},
    {"word":"area","pron":"EH1 R IY0 AH0 .","syllables":[1,0,0]},
    {"word":"bird","pron":"B ER1 D .","syllables":[1]},
    {"word":"toward","pron":"T AH0 W AO1 R D .","syllables":[0,1]},
    {"word":"person","pron":"P ER1 S AH0 N .","syllables":[1,0]},
    {"word":"problem","pron":"P R AA1 B L AH0 M .","syllables":[1,0]},
    {"word":"remember","pron":"R IH0 M EH1 M B ER0 .","syllables":[0,1,0]},
    {"word":"week","pron":"W IY1 K .","syllables":[1]},
    {"word":"west","pron":"W EH1 S T .","syllables":[1]},
    {"word":"note","pron":"N OW1 T .","syllables":[1]},
    {"word":"map","pron":"M AE1 P .","syllables":[1]},
    {"word":"against","pron":"AH0 G EH1 N S T .","syllables":[0,1]},
    {"word":"step","pron":"S T EH1 P .","syllables":[1]},
    {"word":"hold","pron":"HH OW1 L D .","syllables":[1]},
    {"word":"less","pron":"L EH1 S .","syllables":[1]},
    {"word":"road","pron":"R OW1 D .","syllables":[1]},
    {"word":"stood","pron":"S T UH1 D .","syllables":[1]},
    {"word":"cold","pron":"K OW1 L D .","syllables":[1]},
    {"word":"front","pron":"F R AH1 N T .","syllables":[1]},
    {"word":"several","pron":"S EH1 V ER0 AH0 L .","syllables":[1,0,0]},
    {"word":"fly","pron":"F L AY1 .","syllables":[1]},
    {"word":"ocean","pron":"OW1 SH AH0 N .","syllables":[1,0]},
    {"word":"hundred","pron":"HH AH1 N D R AH0 D .","syllables":[1,0]},
    {"word":"lead","pron":"L EH1 D .","syllables":[1]},
    {"word":"machine","pron":"M AH0 SH IY1 N .","syllables":[0,1]},
    {"word":"plan","pron":"P L AE1 N .","syllables":[1]},
    {"word":"teach","pron":"T IY1 CH .","syllables":[1]},
    {"word":"verb","pron":"V ER1 B .","syllables":[1]},
    {"word":"done","pron":"D AH1 N .","syllables":[1]},
    {"word":"tail","pron":"T EY1 L .","syllables":[1]},
    {"word":"beauty","pron":"B Y UW1 T IY0 .","syllables":[1,0]},
    {"word":"final","pron":"F AY1 N AH0 L .","syllables":[1,0]},
    {"word":"rule","pron":"R UW1 L .","syllables":[1]},
    {"word":"contain","pron":"K AH0 N T EY1 N .","syllables":[0,1]},
    {"word":"full","pron":"F UH1 L .","syllables":[1]},
    {"word":"serve","pron":"S ER1 V .","syllables":[1]},
    {"word":"green","pron":"G R IY1 N .","syllables":[1]},
    {"word":"rain","pron":"R EY1 N .","syllables":[1]},
    {"word":"six","pron":"S IH1 K S .","syllables":[1]},
    {"word":"table","pron":"T EY1 B AH0 L .","syllables":[1,0]},
    {"word":"fall","pron":"F AO1 L .","syllables":[1]},
    {"word":"happen","pron":"HH AE1 P AH0 N .","syllables":[1,0]},
    {"word":"pound","pron":"P AW1 N D .","syllables":[1]},
    {"word":"develop","pron":"D IH0 V EH1 L AH0 P .","syllables":[0,1,0]},
    {"word":"simple","pron":"S IH1 M P AH0 L .","syllables":[1,0]},
    {"word":"numeral","pron":"N UW1 M ER0 AH0 L .","syllables":[1,0,0]},
    {"word":"cry","pron":"K R AY1 .","syllables":[1]},
    {"word":"morning","pron":"M AO1 R N IH0 NG .","syllables":[1,0]},
    {"word":"rest","pron":"R EH1 S T .","syllables":[1]},
    {"word":"class","pron":"K L AE1 S .","syllables":[1]},
    {"word":"town","pron":"T AW1 N .","syllables":[1]},
    {"word":"dark","pron":"D AA1 R K .","syllables":[1]},
    {"word":"oh","pron":"OW1 .","syllables":[1]},
    {"word":"behind","pron":"B IH0 HH AY1 N D .","syllables":[0,1]},
    {"word":"warm","pron":"W AO1 R M .","syllables":[1]},
    {"word":"wind","pron":"W AY1 N D .","syllables":[1]},
    {"word":"able","pron":"EY1 B AH0 L .","syllables":[1,0]},
    {"word":"ball","pron":"B AO1 L .","syllables":[1]},
    {"word":"general","pron":"JH EH1 N ER0 AH0 L .","syllables":[1,0,0]},
    {"word":"drop","pron":"D R AA1 P .","syllables":[1]},
    {"word":"weight","pron":"W EY1 T .","syllables":[1]},
    {"word":"ice","pron":"AY1 S .","syllables":[1]},
    {"word":"present","pron":"P R EH1 Z AH0 N T .","syllables":[1,0]},
    {"word":"arm","pron":"AA1 R M .","syllables":[1]},
    {"word":"speak","pron":"S P IY1 K .","syllables":[1]},
    {"word":"material","pron":"M AH0 T IH1 R IY0 AH0 L .","syllables":[0,1,0,0]},
    {"word":"felt","pron":"F EH1 L T .","syllables":[1]},
    {"word":"wave","pron":"W EY1 V .","syllables":[1]},
    {"word":"joy","pron":"JH OY1 .","syllables":[1]},
    {"word":"sat","pron":"S AE1 T .","syllables":[1]},
    {"word":"heart","pron":"HH AA1 R T .","syllables":[1]},
    {"word":"board","pron":"B AO1 R D .","syllables":[1]},
    {"word":"region","pron":"R IY1 JH AH0 N .","syllables":[1,0]},
    {"word":"matter","pron":"M AE1 T ER0 .","syllables":[1,0]},
    {"word":"represent","pron":"R EH2 P R AH0 Z EH1 N T .","syllables":[2,0,1]},
    {"word":"grand","pron":"G R AE1 N D .","syllables":[1]},
    {"word":"include","pron":"IH2 N K L UW1 D .","syllables":[2,1]},
    {"word":"subject","pron":"S AH0 B JH EH1 K T .","syllables":[0,1]},
    {"word":"square","pron":"S K W EH1 R .","syllables":[1]},
    {"word":"syllable","pron":"S IH1 L AH0 B AH0 L .","syllables":[1,0,0]},
    {"word":"engine","pron":"EH1 N JH AH0 N .","syllables":[1,0]},
    {"word":"yet","pron":"Y EH1 T .","syllables":[1]},
    {"word":"wall","pron":"W AO1 L .","syllables":[1]},
    {"word":"length","pron":"L EH1 NG K TH .","syllables":[1]},
    {"word":"forest","pron":"F AO1 R AH0 S T .","syllables":[1,0]},
    {"word":"window","pron":"W IH1 N D OW0 .","syllables":[1,0]},
    {"word":"believe","pron":"B IH0 L IY1 V .","syllables":[0,1]},
    {"word":"pick","pron":"P IH1 K .","syllables":[1]},
    {"word":"race","pron":"R EY1 S .","syllables":[1]},
    {"word":"egg","pron":"EH1 G .","syllables":[1]},
    {"word":"dance","pron":"D AE1 N S .","syllables":[1]},
    {"word":"fraction","pron":"F R AE1 K SH AH0 N .","syllables":[1,0]},
    {"word":"sit","pron":"S IH1 T .","syllables":[1]},
    {"word":"art","pron":"AA1 R T .","syllables":[1]},
    {"word":"village","pron":"V IH1 L AH0 JH .","syllables":[1,0]},
    {"word":"wish","pron":"W IH1 SH .","syllables":[1]},
    {"word":"sky","pron":"S K AY1 .","syllables":[1]},
    {"word":"past","pron":"P AE1 S T .","syllables":[1]},
    {"word":"pay","pron":"P EY1 .","syllables":[1]},
    {"word":"floor","pron":"F L AO1 R .","syllables":[1]},
    {"word":"sign","pron":"S AY1 N .","syllables":[1]},
    {"word":"child","pron":"CH AY1 L D .","syllables":[1]},
    {"word":"hair","pron":"HH EH1 R .","syllables":[1]},
    {"word":"spring","pron":"S P R IH1 NG .","syllables":[1]},
    {"word":"industry","pron":"IH1 N D AH0 S T R IY0 .","syllables":[1,0,0]},
    {"word":"coast","pron":"K OW1 S T .","syllables":[1]},
    {"word":"bright","pron":"B R AY1 T .","syllables":[1]},
    {"word":"solve","pron":"S AA1 L V .","syllables":[1]},
    {"word":"speed","pron":"S P IY1 D .","syllables":[1]},
    {"word":"job","pron":"JH AA1 B .","syllables":[1]},
    {"word":"tiny","pron":"T AY1 N IY0 .","syllables":[1,0]},
    {"word":"finger","pron":"F IH1 NG G ER0 .","syllables":[1,0]},
    {"word":"phrase","pron":"F R EY1 Z .","syllables":[1]},
    {"word":"fun","pron":"F AH1 N .","syllables":[1]},
    {"word":"cat","pron":"K AE1 T .","syllables":[1]},
    {"word":"lake","pron":"L EY1 K .","syllables":[1]},
    {"word":"experiment","pron":"IH0 K S P EH1 R AH0 M AH0 N T .","syllables":[0,1,0,0]},
    {"word":"jump","pron":"JH AH1 M P .","syllables":[1]},
    {"word":"cow","pron":"K AW1 .","syllables":[1]},
    {"word":"metal","pron":"M EH1 T AH0 L .","syllables":[1,0]},
    {"word":"glass","pron":"G L AE1 S .","syllables":[1]},
    {"word":"flat","pron":"F L AE1 T .","syllables":[1]},
    {"word":"twenty","pron":"T W EH1 N T IY0 .","syllables":[1,0]},
    {"word":"fight","pron":"F AY1 T .","syllables":[1]},
    {"word":"weather","pron":"W EH1 DH ER0 .","syllables":[1,0]},
    {"word":"office","pron":"AO1 F AH0 S .","syllables":[1,0]},
    {"word":"observe","pron":"AH0 B Z ER1 V .","syllables":[0,1]},
    {"word":"excite","pron":"IH0 K S AY1 T .","syllables":[0,1]},
    {"word":"soil","pron":"S OY1 L .","syllables":[1]},
    {"word":"exact","pron":"IH0 G Z AE1 K T .","syllables":[0,1]},
    {"word":"design","pron":"D IH0 Z AY1 N .","syllables":[0,1]},
    {"word":"key","pron":"K IY1 .","syllables":[1]},
    {"word":"least","pron":"L IY1 S T .","syllables":[1]},
    {"word":"die","pron":"D AY1 .","syllables":[1]},
    {"word":"son","pron":"S AH1 N .","syllables":[1]},
    {"word":"symbol","pron":"S IH1 M B AH0 L .","syllables":[1,0]},
    {"word":"clean","pron":"K L IY1 N .","syllables":[1]},
    {"word":"mouth","pron":"M AW1 TH .","syllables":[1]},
    {"word":"lot","pron":"L AA1 T .","syllables":[1]},
    {"word":"bottom","pron":"B AA1 T AH0 M .","syllables":[1,0]},
    {"word":"natural","pron":"N AE1 CH ER0 AH0 L .","syllables":[1,0,0]},
    {"word":"cent","pron":"S EH1 N T .","syllables":[1]},
    {"word":"blood","pron":"B L AH1 D .","syllables":[1]},
    {"word":"touch","pron":"T AH1 CH .","syllables":[1]},
    {"word":"rise","pron":"R AY1 Z .","syllables":[1]},
    {"word":"trouble","pron":"T R AH1 B AH0 L .","syllables":[1,0]},
    {"word":"break","pron":"B R EY1 K .","syllables":[1]},
    {"word":"bad","pron":"B AE1 D .","syllables":[1]},
    {"word":"yard","pron":"Y AA1 R D .","syllables":[1]},
    {"word":"oil","pron":"OY1 L .","syllables":[1]},
    {"word":"cost","pron":"K AA1 S T .","syllables":[1]},
    {"word":"team","pron":"T IY1 M .","syllables":[1]},
    {"word":"brown","pron":"B R AW1 N .","syllables":[1]},
    {"word":"lady","pron":"L EY1 D IY0 .","syllables":[1,0]},
    {"word":"ring","pron":"R IH1 NG .","syllables":[1]},
    {"word":"noon","pron":"N UW1 N .","syllables":[1]},
    {"word":"difficult","pron":"D IH1 F AH0 K AH0 L T .","syllables":[1,0,0]},
    {"word":"doctor","pron":"D AA1 K T ER0 .","syllables":[1,0]},
    {"word":"please","pron":"P L IY1 Z .","syllables":[1]},
    {"word":"spoke","pron":"S P OW1 K .","syllables":[1]},
    {"word":"separate","pron":"S EH1 P ER0 EY2 T .","syllables":[1,0,2]},
    {"word":"woman","pron":"W UH1 M AH0 N .","syllables":[1,0]},
    {"word":"protect","pron":"P R AH0 T EH1 K T .","syllables":[0,1]},
    {"word":"locate","pron":"L OW1 K EY2 T .","syllables":[1,2]},
    {"word":"indicate","pron":"IH1 N D AH0 K EY2 T .","syllables":[1,0,2]},
    {"word":"captain","pron":"K AE1 P T AH0 N .","syllables":[1,0]},
    {"word":"whose","pron":"HH UW1 Z .","syllables":[1]},
    {"word":"caught","pron":"K AA1 T .","syllables":[1]},
    {"word":"radio","pron":"R EY1 D IY0 OW2 .","syllables":[1,0,2]},
    {"word":"character","pron":"K EH1 R IH0 K T ER0 .","syllables":[1,0,0]},
    {"word":"period","pron":"P IH1 R IY0 AH0 D .","syllables":[1,0,0]},
    {"word":"insect","pron":"IH1 N S EH2 K T .","syllables":[1,2]},
    {"word":"corner","pron":"K AO1 R N ER0 .","syllables":[1,0]},
    {"word":"party","pron":"P AA1 R T IY0 .","syllables":[1,0]},
    {"word":"bone","pron":"B OW1 N .","syllables":[1]},
    {"word":"supply","pron":"S AH0 P L AY1 .","syllables":[0,1]},
    {"word":"rail","pron":"R EY1 L .","syllables":[1]},
    {"word":"student","pron":"S T UW1 D AH0 N T .","syllables":[1,0]},
    {"word":"element","pron":"EH1 L AH0 M AH0 N T .","syllables":[1,0,0]},
    {"word":"effect","pron":"IH0 F EH1 K T .","syllables":[0,1]},
    {"word":"modern","pron":"M AA1 D ER0 N .","syllables":[1,0]},
    {"word":"crop","pron":"K R AA1 P .","syllables":[1]},
    {"word":"human","pron":"HH Y UW1 M AH0 N .","syllables":[1,0]},
    {"word":"won't","pron":"W OW1 N T .","syllables":[1]},
    {"word":"expect","pron":"IH0 K S P EH1 K T .","syllables":[0,1]},
    {"word":"provide","pron":"P R AH0 V AY1 D .","syllables":[0,1]},
    {"word":"atom","pron":"AE1 T AH0 M .","syllables":[1,0]},
    {"word":"fruit","pron":"F R UW1 T .","syllables":[1]},
    {"word":"thus","pron":"DH AH1 S .","syllables":[1]},
    {"word":"electric","pron":"IH0 L EH1 K T R IH0 K .","syllables":[0,1,0]},
    {"word":"operate","pron":"AA1 P ER0 EY2 T .","syllables":[1,0,2]},
    {"word":"capital","pron":"K AE1 P IH0 T AH0 L .","syllables":[1,0,0]},
    {"word":"agree","pron":"AH0 G R IY1 .","syllables":[0,1]},
    {"word":"chair","pron":"CH EH1 R .","syllables":[1]},
    {"word":"soldier","pron":"S OW1 L JH ER0 .","syllables":[1,0]},
    {"word":"mount","pron":"M AW1 N T .","syllables":[1]},
    {"word":"catch","pron":"K AE1 CH .","syllables":[1]},
    {"word":"brother","pron":"B R AH1 DH ER0 .","syllables":[1,0]},
    {"word":"scale","pron":"S K EY1 L .","syllables":[1]},
    {"word":"third","pron":"TH ER1 D .","syllables":[1]},
    {"word":"lost","pron":"L AO1 S T .","syllables":[1]},
    {"word":"choose","pron":"CH UW1 Z .","syllables":[1]},
    {"word":"wear","pron":"W EH1 R .","syllables":[1]},
    {"word":"mix","pron":"M IH1 K S .","syllables":[1]},
    {"word":"wire","pron":"W AY1 ER0 .","syllables":[1,0]},
    {"word":"practice","pron":"P R AE1 K T IH0 S .","syllables":[1,0]},
    {"word":"shout","pron":"SH AW1 T .","syllables":[1]},
    {"word":"gentle","pron":"JH EH1 N T AH0 L .","syllables":[1,0]},
    {"word":"decimal","pron":"D EH1 S AH0 M AH0 L .","syllables":[1,0,0]},
    {"word":"control","pron":"K AH0 N T R OW1 L .","syllables":[0,1]},
    {"word":"thick","pron":"TH IH1 K .","syllables":[1]},
    {"word":"collect","pron":"K AH0 L EH1 K T .","syllables":[0,1]},
    {"word":"process","pron":"P R AA1 S EH2 S .","syllables":[1,2]},
    {"word":"imagine","pron":"IH2 M AE1 JH AH0 N .","syllables":[2,1,0]},
    {"word":"save","pron":"S EY1 V .","syllables":[1]},
    {"word":"bank","pron":"B AE1 NG K .","syllables":[1]},
    {"word":"rich","pron":"R IH1 CH .","syllables":[1]},
    {"word":"flow","pron":"F L OW1 .","syllables":[1]},
    {"word":"fit","pron":"F IH1 T .","syllables":[1]},
    {"word":"hit","pron":"HH IH1 T .","syllables":[1]},
    {"word":"history","pron":"HH IH1 S T ER0 IY0 .","syllables":[1,0,0]},
    {"word":"equal","pron":"IY1 K W AH0 L .","syllables":[1,0]},
    {"word":"fell","pron":"F EH1 L .","syllables":[1]},
    {"word":"danger","pron":"D EY1 N JH ER0 .","syllables":[1,0]},
    {"word":"fair","pron":"F EH1 R .","syllables":[1]},
    {"word":"sent","pron":"S EH1 N T .","syllables":[1]},
    {"word":"garden","pron":"G AA1 R D AH0 N .","syllables":[1,0]},
    {"word":"circle","pron":"S ER1 K AH0 L .","syllables":[1,0]},
    {"word":"size","pron":"S AY1 Z .","syllables":[1]},
    {"word":"hunt","pron":"HH AH1 N T .","syllables":[1]},
    {"word":"position","pron":"P AH0 Z IH1 SH AH0 N .","syllables":[0,1,0]},
    {"word":"sail","pron":"S EY1 L .","syllables":[1]},
    {"word":"settle","pron":"S EH1 T AH0 L .","syllables":[1,0]},
    {"word":"probable","pron":"P R AA1 B AH0 B AH0 L .","syllables":[1,0,0]},
    {"word":"heavy","pron":"HH EH1 V IY0 .","syllables":[1,0]},
    {"word":"vary","pron":"V EH1 R IY0 .","syllables":[1,0]},
    {"word":"whether","pron":"W EH1 DH ER0 .","syllables":[1,0]},
    {"word":"wide","pron":"W AY1 D .","syllables":[1]},
    {"word":"count","pron":"K AW1 N T .","syllables":[1]},
    {"word":"clothe","pron":"K L OW1 DH .","syllables":[1]},
    {"word":"meet","pron":"M IY1 T .","syllables":[1]},
    {"word":"edge","pron":"EH1 JH .","syllables":[1]},
    {"word":"bed","pron":"B EH1 D .","syllables":[1]},
    {"word":"buy","pron":"B AY1 .","syllables":[1]},
    {"word":"prove","pron":"P R UW1 V .","syllables":[1]},
    {"word":"lone","pron":"L OW1 N .","syllables":[1]},
    {"word":"divide","pron":"D IH0 V AY1 D .","syllables":[0,1]},
    {"word":"written","pron":"R IH1 T AH0 N .","syllables":[1,0]},
    {"word":"baby","pron":"B EY1 B IY0 .","syllables":[1,0]},
    {"word":"ride","pron":"R AY1 D .","syllables":[1]},
    {"word":"finish","pron":"F IH1 N IH0 SH .","syllables":[1,0]},
    {"word":"nation","pron":"N EY1 SH AH0 N .","syllables":[1,0]},
    {"word":"am","pron":"AE1 M .","syllables":[1]},
    {"word":"gone","pron":"G AO1 N .","syllables":[1]},
    {"word":"push","pron":"P UH1 SH .","syllables":[1]},
    {"word":"visit","pron":"V IH1 Z IH0 T .","syllables":[1,0]},
    {"word":"raise","pron":"R EY1 Z .","syllables":[1]},
    {"word":"lie","pron":"L AY1 .","syllables":[1]},
    {"word":"eight","pron":"EY1 T .","syllables":[1]},
    {"word":"receive","pron":"R AH0 S IY1 V .","syllables":[0,1]},
    {"word":"grass","pron":"G R AE1 S .","syllables":[1]},
    {"word":"instrument","pron":"IH1 N S T R AH0 M AH0 N T .","syllables":[1,0,0]},
    {"word":"cell","pron":"S EH1 L .","syllables":[1]},
    {"word":"milk","pron":"M IH1 L K .","syllables":[1]},
    {"word":"roll","pron":"R OW1 L .","syllables":[1]},
    {"word":"stone","pron":"S T OW1 N .","syllables":[1]},
    {"word":"poor","pron":"P UW1 R .","syllables":[1]},
    {"word":"root","pron":"R UW1 T .","syllables":[1]},
    {"word":"either","pron":"IY1 DH ER0 .","syllables":[1,0]},
    {"word":"silent","pron":"S AY1 L AH0 N T .","syllables":[1,0]},
    {"word":"tall","pron":"T AO1 L .","syllables":[1]},
    {"word":"climb","pron":"K L AY1 M .","syllables":[1]},
    {"word":"method","pron":"M EH1 TH AH0 D .","syllables":[1,0]},
    {"word":"paragraph","pron":"P AE1 R AH0 G R AE2 F .","syllables":[1,0,2]},
    {"word":"hole","pron":"HH OW1 L .","syllables":[1]},
    {"word":"iron","pron":"AY1 ER0 N .","syllables":[1,0]},
    {"word":"cool","pron":"K UW1 L .","syllables":[1]},
    {"word":"cook","pron":"K UH1 K .","syllables":[1]},
    {"word":"blow","pron":"B L OW1 .","syllables":[1]},
    {"word":"strange","pron":"S T R EY1 N JH .","syllables":[1]},
    {"word":"single","pron":"S IH1 NG G AH0 L .","syllables":[1,0]},
    {"word":"grew","pron":"G R UW1 .","syllables":[1]},
    {"word":"store","pron":"S T AO1 R .","syllables":[1]},
    {"word":"tone","pron":"T OW1 N .","syllables":[1]},
    {"word":"wild","pron":"W AY1 L D .","syllables":[1]},
    {"word":"reason","pron":"R IY1 Z AH0 N .","syllables":[1,0]},
    {"word":"row","pron":"R OW1 .","syllables":[1]},
    {"word":"seed","pron":"S IY1 D .","syllables":[1]},
    {"word":"trip","pron":"T R IH1 P .","syllables":[1]},
    {"word":"wrote","pron":"R OW1 T .","syllables":[1]},
    {"word":"crease","pron":"K R IY1 S .","syllables":[1]},
    {"word":"join","pron":"JH OY1 N .","syllables":[1]},
    {"word":"straight","pron":"S T R EY1 T .","syllables":[1]},
    {"word":"suggest","pron":"S AH0 JH EH1 S T .","syllables":[0,1]},
    {"word":"dictionary","pron":"D IH1 K SH AH0 N EH2 R IY0 .","syllables":[1,0,2,0]},
    {"word":"quiet","pron":"K W AY1 AH0 T .","syllables":[1,0]},
    {"word":"cloud","pron":"K L AW1 D .","syllables":[1]},
    {"word":"loud","pron":"L AW1 D .","syllables":[1]},
    {"word":"view","pron":"V Y UW1 .","syllables":[1]},
    {"word":"hill","pron":"HH IH1 L .","syllables":[1]},
    {"word":"broke","pron":"B R OW1 K .","syllables":[1]},
    {"word":"seven","pron":"S EH1 V AH0 N .","syllables":[1,0]},
    {"word":"burn","pron":"B ER1 N .","syllables":[1]},
    {"word":"quite","pron":"K W AY1 T .","syllables":[1]},
    {"word":"temperature","pron":"T EH1 M P R AH0 CH ER0 .","syllables":[1,0,0]},
    {"word":"value","pron":"V AE1 L Y UW0 .","syllables":[1,0]},
    {"word":"sand","pron":"S AE1 N D .","syllables":[1]},
    {"word":"held","pron":"HH EH1 L D .","syllables":[1]},
    {"word":"type","pron":"T AY1 P .","syllables":[1]},
    {"word":"describe","pron":"D IH0 S K R AY1 B .","syllables":[0,1]},
    {"word":"copy","pron":"K AA1 P IY0 .","syllables":[1,0]},
    {"word":"sudden","pron":"S AH1 D AH0 N .","syllables":[1,0]},
    {"word":"pair","pron":"P EH1 R .","syllables":[1]},
    {"word":"winter","pron":"W IH1 N T ER0 .","syllables":[1,0]},
    {"word":"summer","pron":"S AH1 M ER0 .","syllables":[1,0]},
    {"word":"soft","pron":"S AA1 F T .","syllables":[1]},
    {"word":"flower","pron":"F L AW1 ER0 .","syllables":[1,0]},
    {"word":"exercise","pron":"EH1 K S ER0 S AY2 Z .","syllables":[1,0,2]},
    {"word":"kept","pron":"K EH1 P T .","syllables":[1]},
    {"word":"energy","pron":"EH1 N ER0 JH IY0 .","syllables":[1,0,0]},
    {"word":"happy","pron":"HH AE1 P IY0 .","syllables":[1,0]},
    {"word":"sleep","pron":"S L IY1 P .","syllables":[1]},
    {"word":"hope","pron":"HH OW1 P .","syllables":[1]},
    {"word":"million","pron":"M IH1 L Y AH0 N .","syllables":[1,0]},
    {"word":"leg","pron":"L EH1 G .","syllables":[1]},
    {"word":"train","pron":"T R EY1 N .","syllables":[1]},
    {"word":"bit","pron":"B IH1 T .","syllables":[1]},
    {"word":"bear","pron":"B EH1 R .","syllables":[1]},
    {"word":"perhaps","pron":"P ER0 HH AE1 P S .","syllables":[0,1]},
    {"word":"surprise","pron":"S ER0 P R AY1 Z .","syllables":[0,1]},
    {"word":"shall","pron":"SH AE1 L .","syllables":[1]},
    {"word":"consonant","pron":"K AA1 N S AH0 N AH0 N T .","syllables":[1,0,0]},
    {"word":"kill","pron":"K IH1 L .","syllables":[1]},
    {"word":"case","pron":"K EY1 S .","syllables":[1]},
    {"word":"moment","pron":"M OW1 M AH0 N T .","syllables":[1,0]},
    {"word":"melody","pron":"M EH1 L AH0 D IY0 .","syllables":[1,0,0]},
    {"word":"organ","pron":"AO1 R G AH0 N .","syllables":[1,0]},
    {"word":"trade","pron":"T R EY1 D .","syllables":[1]},
    {"word":"smile","pron":"S M AY1 L .","syllables":[1]},
    {"word":"section","pron":"S EH1 K SH AH0 N .","syllables":[1,0]},
    {"word":"safe","pron":"S EY1 F .","syllables":[1]},
    {"word":"age","pron":"EY1 JH .","syllables":[1]},
    {"word":"law","pron":"L AO1 .","syllables":[1]},
    {"word":"gas","pron":"G AE1 S .","syllables":[1]},
    {"word":"stick","pron":"S T IH1 K .","syllables":[1]},
    {"word":"except","pron":"IH0 K S EH1 P T .","syllables":[0,1]},
    {"word":"dress","pron":"D R EH1 S .","syllables":[1]},
    {"word":"middle","pron":"M IH1 D AH0 L .","syllables":[1,0]},
    {"word":"skin","pron":"S K IH1 N .","syllables":[1]},
    {"word":"month","pron":"M AH1 N TH .","syllables":[1]},
    {"word":"consider","pron":"K AH0 N S IH1 D ER0 .","syllables":[0,1,0]},
    {"word":"century","pron":"S EH1 N CH ER0 IY0 .","syllables":[1,0,0]},
    {"word":"ear","pron":"IY1 R .","syllables":[1]},
    {"word":"result","pron":"R IH0 Z AH1 L T .","syllables":[0,1]},
    {"word":"else","pron":"EH1 L S .","syllables":[1]},
    {"word":"sense","pron":"S EH1 N S .","syllables":[1]},
    {"word":"beat","pron":"B IY1 T .","syllables":[1]},
    {"word":"stream","pron":"S T R IY1 M .","syllables":[1]},
    {"word":"wing","pron":"W IH1 NG .","syllables":[1]},
    {"word":"tube","pron":"T UW1 B .","syllables":[1]},
    {"word":"yellow","pron":"Y EH1 L OW0 .","syllables":[1,0]},
    {"word":"create","pron":"K R IY0 EY1 T .","syllables":[0,1]},
    {"word":"sharp","pron":"SH AA1 R P .","syllables":[1]},
    {"word":"thin","pron":"TH IH1 N .","syllables":[1]},
    {"word":"rather","pron":"R AE1 DH ER0 .","syllables":[1,0]},
    {"word":"wash","pron":"W AA1 SH .","syllables":[1]},
    {"word":"bat","pron":"B AE1 T .","syllables":[1]},
    {"word":"crowd","pron":"K R AW1 D .","syllables":[1]},
    {"word":"necessary","pron":"N EH1 S AH0 S EH2 R IY0 .","syllables":[1,0,2,0]},
    {"word":"fear","pron":"F IH1 R .","syllables":[1]},
    {"word":"allow","pron":"AH0 L AW1 .","syllables":[0,1]},
    {"word":"guess","pron":"G EH1 S .","syllables":[1]},
    {"word":"colony","pron":"K AA1 L AH0 N IY0 .","syllables":[1,0,0]},
    {"word":"enter","pron":"EH1 N T ER0 .","syllables":[1,0]},
    {"word":"send","pron":"S EH1 N D .","syllables":[1]},
    {"word":"mine","pron":"M AY1 N .","syllables":[1]},
    {"word":"gun","pron":"G AH1 N .","syllables":[1]},
    {"word":"triangle","pron":"T R AY1 AE2 NG G AH0 L .","syllables":[1,2,0]},
    {"word":"rub","pron":"R AH1 B .","syllables":[1]},
    {"word":"famous","pron":"F EY1 M AH0 S .","syllables":[1,0]},
    {"word":"deal","pron":"D IY1 L .","syllables":[1]},
    {"word":"rose","pron":"R OW1 Z .","syllables":[1]},
    {"word":"block","pron":"B L AA1 K .","syllables":[1]},
    {"word":"spread","pron":"S P R EH1 D .","syllables":[1]},
    {"word":"suit","pron":"S UW1 T .","syllables":[1]},
    {"word":"nine","pron":"N AY1 N .","syllables":[1]},
    {"word":"term","pron":"T ER1 M .","syllables":[1]},
    {"word":"shoulder","pron":"SH OW1 L D ER0 .","syllables":[1,0]},
    {"word":"event","pron":"IH0 V EH1 N T .","syllables":[0,1]},
    {"word":"sell","pron":"S EH1 L .","syllables":[1]},
    {"word":"opposite","pron":"AA1 P AH0 Z IH0 T .","syllables":[1,0,0]},
    {"word":"level","pron":"L EH1 V AH0 L .","syllables":[1,0]},
    {"word":"success","pron":"S AH0 K S EH1 S .","syllables":[0,1]},
    {"word":"company","pron":"K AH1 M P AH0 N IY2 .","syllables":[1,0,2]},
    {"word":"shop","pron":"SH AA1 P .","syllables":[1]},
    {"word":"pitch","pron":"P IH1 CH .","syllables":[1]},
    {"word":"death","pron":"D EH1 TH .","syllables":[1]},
    {"word":"chance","pron":"CH AE1 N S .","syllables":[1]},
    {"word":"throw","pron":"TH R OW1 .","syllables":[1]},
    {"word":"subtract","pron":"S AH0 B T R AE1 K T .","syllables":[0,1]},
    {"word":"nose","pron":"N OW1 Z .","syllables":[1]},
    {"word":"anger","pron":"AE1 NG G ER0 .","syllables":[1,0]},
    {"word":"determine","pron":"D AH0 T ER1 M AH0 N .","syllables":[0,1,0]},
    {"word":"skill","pron":"S K IH1 L .","syllables":[1]},
    {"word":"chart","pron":"CH AA1 R T .","syllables":[1]},
    {"word":"nor","pron":"N AO1 R .","syllables":[1]},
    {"word":"match","pron":"M AE1 CH .","syllables":[1]},
    {"word":"thank","pron":"TH AE1 NG K .","syllables":[1]},
    {"word":"suffix","pron":"S AH1 F IH0 K S .","syllables":[1,0]},
    {"word":"dream","pron":"D R IY1 M .","syllables":[1]},
    {"word":"pretty","pron":"P R IH1 T IY0 .","syllables":[1,0]},
    {"word":"led","pron":"L EH1 D .","syllables":[1]},
    {"word":"oxygen","pron":"AA1 K S AH0 JH AH0 N .","syllables":[1,0,0]},
    {"word":"experience","pron":"IH0 K S P IH1 R IY0 AH0 N S .","syllables":[0,1,0,0]},
    {"word":"similar","pron":"S IH1 M AH0 L ER0 .","syllables":[1,0,0]},
    {"word":"branch","pron":"B R AE1 N CH .","syllables":[1]},
    {"word":"guide","pron":"G AY1 D .","syllables":[1]},
    {"word":"smell","pron":"S M EH1 L .","syllables":[1]},
    {"word":"slave","pron":"S L EY1 V .","syllables":[1]},
    {"word":"proper","pron":"P R AA1 P ER0 .","syllables":[1,0]},
    {"word":"substance","pron":"S AH1 B S T AH0 N S .","syllables":[1,0]},
    {"word":"spend","pron":"S P EH1 N D .","syllables":[1]},
    {"word":"bread","pron":"B R EH1 D .","syllables":[1]},
    {"word":"charge","pron":"CH AA1 R JH .","syllables":[1]},
    {"word":"station","pron":"S T EY1 SH AH0 N .","syllables":[1,0]},
    {"word":"original","pron":"ER0 IH1 JH AH0 N AH0 L .","syllables":[0,1,0,0]},
    {"word":"chick","pron":"CH IH1 K .","syllables":[1]},
    {"word":"dad","pron":"D AE1 D .","syllables":[1]},
    {"word":"instant","pron":"IH1 N S T AH0 N T .","syllables":[1,0]},
    {"word":"degree","pron":"D IH0 G R IY1 .","syllables":[0,1]},
    {"word":"duck","pron":"D AH1 K .","syllables":[1]},
    {"word":"division","pron":"D IH0 V IH1 ZH AH0 N .","syllables":[0,1,0]},
    {"word":"favor","pron":"F EY1 V ER0 .","syllables":[1,0]},
    {"word":"enemy","pron":"EH1 N AH0 M IY0 .","syllables":[1,0,0]},
    {"word":"condition","pron":"K AH0 N D IH1 SH AH0 N .","syllables":[0,1,0]},
    {"word":"market","pron":"M AA1 R K AH0 T .","syllables":[1,0]},
    {"word":"connect","pron":"K AH0 N EH1 K T .","syllables":[0,1]},
    {"word":"share","pron":"SH EH1 R .","syllables":[1]},
    {"word":"master","pron":"M AE1 S T ER0 .","syllables":[1,0]},
    {"word":"glad","pron":"G L AE1 D .","syllables":[1]},
    {"word":"sheet","pron":"SH IY1 T .","syllables":[1]},
    {"word":"apple","pron":"AE1 P AH0 L .","syllables":[1,0]},
    {"word":"drink","pron":"D R IH1 NG K .","syllables":[1]},
    {"word":"fat","pron":"F AE1 T .","syllables":[1]},
    {"word":"speech","pron":"S P IY1 CH .","syllables":[1]},
    {"word":"log","pron":"L AO1 G .","syllables":[1]},
    {"word":"steam","pron":"S T IY1 M .","syllables":[1]},
    {"word":"liquid","pron":"L IH1 K W AH0 D .","syllables":[1,0]},
    {"word":"meant","pron":"M EH1 N T .","syllables":[1]},
    {"word":"motion","pron":"M OW1 SH AH0 N .","syllables":[1,0]},
    {"word":"occur","pron":"AH0 K ER1 .","syllables":[0,1]},
    {"word":"teeth","pron":"T IY1 TH .","syllables":[1]},
    {"word":"fresh","pron":"F R EH1 SH .","syllables":[1]},
    {"word":"dollar","pron":"D AA1 L ER0 .","syllables":[1,0]},
    {"word":"segment","pron":"S EH1 G M AH0 N T .","syllables":[1,0]},
    {"word":"offer","pron":"AO1 F ER0 .","syllables":[1,0]},
    {"word":"valley","pron":"V AE1 L IY0 .","syllables":[1,0]},
    {"word":"wife","pron":"W AY1 F .","syllables":[1]},
    {"word":"noise","pron":"N OY1 Z .","syllables":[1]},
    {"word":"basic","pron":"B EY1 S IH0 K .","syllables":[1,0]},
    {"word":"neighbor","pron":"N EY1 B ER0 .","syllables":[1,0]},
    {"word":"tool","pron":"T UW1 L .","syllables":[1]},
    {"word":"bar","pron":"B AA1 R .","syllables":[1]},
    {"word":"shell","pron":"SH EH1 L .","syllables":[1]},
    {"word":"post","pron":"P OW1 S T .","syllables":[1]},
    {"word":"rope","pron":"R OW1 P .","syllables":[1]},
    {"word":"chord","pron":"K AO1 R D .","syllables":[1]},
    {"word":"claim","pron":"K L EY1 M .","syllables":[1]},
    {"word":"especially","pron":"AH0 S P EH1 SH L IY0 .","syllables":[0,1,0]},
    {"word":"reply","pron":"R IH0 P L AY1 .","syllables":[0,1]},
    {"word":"band","pron":"B AE1 N D .","syllables":[1]},
    {"word":"afraid","pron":"AH0 F R EY1 D .","syllables":[0,1]},
    {"word":"sister","pron":"S IH1 S T ER0 .","syllables":[1,0]},
    {"word":"plural","pron":"P L UH1 R AH0 L .","syllables":[1,0]},
    {"word":"property","pron":"P R AA1 P ER0 T IY0 .","syllables":[1,0,0]},
    {"word":"shine","pron":"SH AY1 N .","syllables":[1]},
    {"word":"slip","pron":"S L IH1 P .","syllables":[1]},
    {"word":"broad","pron":"B R AO1 D .","syllables":[1]},
    {"word":"truck","pron":"T R AH1 K .","syllables":[1]},
    {"word":"sight","pron":"S AY1 T .","syllables":[1]},
    {"word":"poem","pron":"P OW1 AH0 M .","syllables":[1,0]},
    {"word":"desert","pron":"D EH1 Z ER0 T .","syllables":[1,0]},
    {"word":"string","pron":"S T R IH1 NG .","syllables":[1]},
    {"word":"bell","pron":"B EH1 L .","syllables":[1]},
    {"word":"stretch","pron":"S T R EH1 CH .","syllables":[1]},
    {"word":"lift","pron":"L IH1 F T .","syllables":[1]},
    {"word":"dead","pron":"D EH1 D .","syllables":[1]},
    {"word":"camp","pron":"K AE1 M P .","syllables":[1]},
    {"word":"search","pron":"S ER1 CH .","syllables":[1]},
    {"word":"chief","pron":"CH IY1 F .","syllables":[1]},
    {"word":"current","pron":"K ER1 AH0 N T .","syllables":[1,0]},
    {"word":"depend","pron":"D IH0 P EH1 N D .","syllables":[0,1]},
    {"word":"corn","pron":"K AO1 R N .","syllables":[1]},
    {"word":"quart","pron":"K W AO1 R T .","syllables":[1]},
    {"word":"compare","pron":"K AH0 M P EH1 R .","syllables":[0,1]},
    {"word":"print","pron":"P R IH1 N T .","syllables":[1]},
    {"word":"spot","pron":"S P AA1 T .","syllables":[1]},
    {"word":"support","pron":"S AH0 P AO1 R T .","syllables":[0,1]},
    {"word":"meat","pron":"M IY1 T .","syllables":[1]},
    {"word":"path","pron":"P AE1 TH .","syllables":[1]},
    {"word":"neck","pron":"N EH1 K .","syllables":[1]},
    {"word":"nature","pron":"N EY1 CH ER0 .","syllables":[1,0]},
    {"word":"dear","pron":"D IH1 R .","syllables":[1]},
    {"word":"populate","pron":"P AA1 P Y AH0 L EY2 T .","syllables":[1,0,2]},
    {"word":"range","pron":"R EY1 N JH .","syllables":[1]},
    {"word":"quotient","pron":"K W OW1 SH AH0 N T .","syllables":[1,0]},
    {"word":"born","pron":"B AO1 R N .","syllables":[1]},
    {"word":"continue","pron":"K AH0 N T IH1 N Y UW0 .","syllables":[0,1,0]},
    {"word":"cotton","pron":"K AA1 T AH0 N .","syllables":[1,0]},
    {"word":"huge","pron":"HH Y UW1 JH .","syllables":[1]},
    {"word":"continent","pron":"K AA1 N T AH0 N AH0 N T .","syllables":[1,0,0]},
    {"word":"molecule","pron":"M AA1 L AH0 K Y UW2 L .","syllables":[1,0,2]},
    {"word":"prepare","pron":"P R IY0 P EH1 R .","syllables":[0,1]},
    {"word":"invent","pron":"IH2 N V EH1 N T .","syllables":[2,1]},
    {"word":"sugar","pron":"SH UH1 G ER0 .","syllables":[1,0]},
    {"word":"arrange","pron":"ER0 EY1 N JH .","syllables":[0,1]},
    {"word":"season","pron":"S IY1 Z AH0 N .","syllables":[1,0]},
    {"word":"salt","pron":"S AO1 L T .","syllables":[1]},
    {"word":"silver","pron":"S IH1 L V ER0 .","syllables":[1,0]},
    {"word":"select","pron":"S AH0 L EH1 K T .","syllables":[0,1]},
    {"word":"fig","pron":"F IH1 G .","syllables":[1]},
    {"word":"feed","pron":"F IY1 D .","syllables":[1]},
    {"word":"wrong","pron":"R AO1 NG .","syllables":[1]},
    {"word":"repeat","pron":"R IH0 P IY1 T .","syllables":[0,1]},
    {"word":"shoe","pron":"SH UW1 .","syllables":[1]},
    {"word":"bought","pron":"B AA1 T .","syllables":[1]},
    {"word":"discuss","pron":"D IH0 S K AH1 S .","syllables":[0,1]},
    {"word":"evening","pron":"IY1 V N IH0 NG .","syllables":[1,0]},
    {"word":"women","pron":"W IH1 M AH0 N .","syllables":[1,0]},
    {"word":"coat","pron":"K OW1 T .","syllables":[1]},
    {"word":"card","pron":"K AA1 R D .","syllables":[1]},
    {"word":"solution","pron":"S AH0 L UW1 SH AH0 N .","syllables":[0,1,0]},
    {"word":"track","pron":"T R AE1 K .","syllables":[1]},
    {"word":"double","pron":"D AH1 B AH0 L .","syllables":[1,0]},
    {"word":"win","pron":"W IH1 N .","syllables":[1]},
    {"word":"seat","pron":"S IY1 T .","syllables":[1]},
    {"word":"arrive","pron":"ER0 AY1 V .","syllables":[0,1]},
    {"word":"score","pron":"S K AO1 R .","syllables":[1]},
    {"word":"gray","pron":"G R EY1 .","syllables":[1]},
    {"word":"parent","pron":"P EH1 R AH0 N T .","syllables":[1,0]},
    {"word":"shore","pron":"SH AO1 R .","syllables":[1]},
    {"word":"planet","pron":"P L AE1 N AH0 T .","syllables":[1,0]},
    {"word":"particular","pron":"P ER0 T IH1 K Y AH0 L ER0 .","syllables":[0,1,0,0]},
    {"word":"clock","pron":"K L AA1 K .","syllables":[1]},
    {"word":"gather","pron":"G AE1 DH ER0 .","syllables":[1,0]},
    {"word":"total","pron":"T OW1 T AH0 L .","syllables":[1,0]},
    {"word":"tie","pron":"T AY1 .","syllables":[1]},
    {"word":"hurry","pron":"HH ER1 IY0 .","syllables":[1,0]},
    {"word":"magnet","pron":"M AE1 G N AH0 T .","syllables":[1,0]},
    {"word":"mass","pron":"M AE1 S .","syllables":[1]},
    {"word":"steel","pron":"S T IY1 L .","syllables":[1]},
    {"word":"forward","pron":"F AO1 R W ER0 D .","syllables":[1,0]},
    {"word":"require","pron":"R IY2 K W AY1 ER0 .","syllables":[2,1,0]},
    {"word":"column","pron":"K AA1 L AH0 M .","syllables":[1,0]},
    {"word":"major","pron":"M EY1 JH ER0 .","syllables":[1,0]},
    {"word":"hat","pron":"HH AE1 T .","syllables":[1]},
    {"word":"swim","pron":"S W IH1 M .","syllables":[1]}
  ]
};